baseURL: https://fairlingtonhistoricalsociety.pages.dev/
languageCode: en-us
title: Fairlington Historical Society
theme: 
- hugo-book
buildFuture: true

timeout: 300000

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  BookTheme: auto
  BookLogo: favicon.png
  description: Fairlington Historical Society
  images: ["share/share.jpg"]
#  twitter: "@FairlingtonHistoricalSociety"
#  fb: FairlingtonHistoricalSociety
  title: Fairlington Historical Society
  BookSection: '*'
  booktoc: false

permalinks:
  about: /:sections[1:]/:filename/
  posts: /:year/:month/:day/:slug/

copyright: Fairlington Historical Society
defaultContentLanguage: en
languages:
  en:
    weight: 1
    languageName: English
    title: Fairlington Historical Society
